# Generated by Django 5.1.4 on 2025-07-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField()),
                ('runtime', models.FloatField()),
                ('genre', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('mpaa_rating', models.CharField(max_length=20)),
                ('predicted_revenue', models.FloatField()),
                ('model_used', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
