# Generated by Django 5.1.4 on 2025-07-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('predicted_rainfall', models.FloatField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PredictionRecord',
        ),
    ]
