# Generated by Django 5.1.4 on 2025-07-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_patientdata_delete_rainfallinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
