# Generated by Django 5.1.4 on 2025-07-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_patientdata_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientData',
        ),
    ]
