# Generated by Django 5.1.4 on 2025-07-19 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_patientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.FloatField(help_text='in cm')),
                ('weight', models.FloatField(help_text='in kg')),
                ('blood_pressure', models.FloatField(help_text='Systolic e.g., 120')),
                ('medication', models.BooleanField(default=False)),
                ('allergy', models.BooleanField(default=False)),
                ('family_history', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('lifestyle', models.CharField(choices=[('sedentary', 'Sedentary'), ('active', 'Active'), ('athletic', 'Athletic')], default='sedentary', max_length=10)),
                ('predicted_diseases', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
