# Generated by Django 5.1.4 on 2025-07-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_patientdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientData',
        ),
    ]
