# Generated by Django 5.1.4 on 2025-07-19 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_patientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('diagnosis_date', models.DateField()),
                ('medications', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('smoking_alcohol_use', models.TextField(blank=True)),
                ('lifestyle_factors', models.TextField(blank=True)),
                ('predicted_diseases', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
