# Generated by Django 5.1.4 on 2025-07-19 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_patientdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='smoking_alcohol_use',
        ),
        migrations.AddField(
            model_name='patientdata',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='chest_pain',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='genetic_mutation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='physical_activity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='shortness_of_breath',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='stress',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='age',
            field=models.PositiveIntegerField(help_text='Enter age between 1 and 120', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='blood_pressure',
            field=models.FloatField(blank=True, help_text='Systolic BP in mmHg (50 - 250)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='family_history',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in centimeters (30 - 300 cm)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kilograms (2 - 500 kg)', null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
