# Generated by Django 5.1.4 on 2025-07-19 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_patientdata_smoking_alcohol_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='age',
            field=models.PositiveIntegerField(help_text='Enter age between 10 and 90', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
