# Generated by Django 5.1.4 on 2025-07-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_patientdata_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('blood_pressure', models.PositiveSmallIntegerField()),
                ('diagnosis_year', models.PositiveIntegerField()),
                ('medications', models.CharField(choices=[('None', 'None'), ('Steroids', 'Steroids'), ('Insulin', 'Insulin'), ('Antidepressants', 'Antidepressants')], max_length=50)),
                ('allergies', models.CharField(choices=[('None', 'None'), ('Dust', 'Dust'), ('Pollen', 'Pollen'), ('Food', 'Food')], max_length=50)),
                ('family_history', models.CharField(choices=[('None', 'None'), ('Asthma', 'Asthma'), ('Diabetes', 'Diabetes'), ('Depression', 'Depression'), ('All', 'All')], max_length=50)),
                ('smoking', models.BooleanField()),
                ('alcohol_use', models.BooleanField()),
                ('exercise_freq', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('diet_quality', models.CharField(choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good')], max_length=10)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.DeleteModel(
            name='PatientData',
        ),
    ]
