# Generated by Django 5.1.4 on 2025-07-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(choices=[('None', 'None'), ('Dust', 'Dust'), ('Pollen', 'Pollen'), ('Food', 'Food'), ('Insect', 'Insect'), ('Medicine', 'Medicine'), ('Pet dander', 'Pet dander'), ('Mold', 'Mold'), ('Latex', 'Latex'), ('Nuts', 'Nuts'), ('Dairy', 'Dairy'), ('Gluten', 'Gluten'), ('Shellfish', 'Shellfish'), ('Soy', 'Soy'), ('Eggs', 'Eggs'), ('Fragrances', 'Fragrances'), ('Chemical', 'Chemical'), ('Nickel', 'Nickel'), ('Sunlight (Photosensitivity)', 'Sunlight (Photosensitivity)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=models.CharField(choices=[('None', 'None'), ('Steroids', 'Steroids'), ('Insulin', 'Insulin'), ('Antidepressants', 'Antidepressants'), ('Antihistamines', 'Antihistamines'), ('Beta blockers', 'Beta blockers'), ('Antibiotics', 'Antibiotics'), ('Antipsychotics', 'Antipsychotics'), ('Antacids', 'Antacids'), ('Painkillers', 'Painkillers'), ('Blood thinners', 'Blood thinners'), ('Diuretics', 'Diuretics'), ('Hormone therapy', 'Hormone therapy'), ('Anticonvulsants', 'Anticonvulsants'), ('Immunosuppressants', 'Immunosuppressants'), ('Chemotherapy', 'Chemotherapy'), ('Thyroid medication', 'Thyroid medication'), ('Statins', 'Statins'), ('Bronchodilators', 'Bronchodilators'), ('Oral contraceptives', 'Oral contraceptives')], max_length=50),
        ),
    ]
