# Generated by Django 5.1.4 on 2025-07-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
