# Generated by Django 5.1.4 on 2025-07-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_patient_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100)),
                ('use', models.TextField()),
                ('advantages', models.TextField()),
                ('disadvantages', models.TextField()),
                ('sample_code', models.TextField()),
                ('pin_wiring', models.TextField()),
                ('notes', models.TextField()),
                ('original_image', models.ImageField(upload_to='sensor_images/original/')),
                ('grayscale_image', models.ImageField(null=True, upload_to='sensor_images/grayscale/')),
                ('equalized_image', models.ImageField(null=True, upload_to='sensor_images/equalized/')),
                ('blurred_image', models.ImageField(null=True, upload_to='sensor_images/blurred/')),
                ('thresholded_image', models.ImageField(null=True, upload_to='sensor_images/thresholded/')),
                ('roi_image', models.ImageField(null=True, upload_to='sensor_images/roi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
