# Generated by Django 5.1.4 on 2025-10-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_sensorprediction_delete_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorPrediction',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
