# Generated by Django 5.1.4 on 2025-10-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_sensorprediction_message_encrypted_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kem_pk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kem_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sign_pk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sign_sk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
